@baseUrl = http://localhost:3000

# Recados
GET {{baseUrl}}/recados

###

# Recado por id

GET {{baseUrl}}/recados/20

###

POST {{baseUrl}}/recados
Content-Type: application/json

{
    "recado": "Recado qualquer."
}